"""delete unneccesary table

Revision ID: 03024dffbf21
Revises: 439afb597fe2
Create Date: 2025-03-02 15:09:20.317807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '03024dffbf21'
down_revision = '439afb597fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_result')
    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.drop_column('last_executed_at')
        batch_op.drop_column('execution_time')
        batch_op.drop_column('expected_result')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_result', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('execution_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_executed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    op.create_table('test_result',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test_case_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('result', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('executed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('log', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], name='test_result_test_case_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='test_result_pkey')
    )
    # ### end Alembic commands ###
