"""add new models and ajust

Revision ID: f108f81f7ba7
Revises: 1744a1c554b7
Create Date: 2025-04-12 09:12:27.083321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f108f81f7ba7'
down_revision = '1744a1c554b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_text', sa.Text(), nullable=False),
    sa.Column('test_case_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('embedding', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rag_reference')
    # ### end Alembic commands ###
